CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE vehicles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration VARCHAR(20)  NOT NULL UNIQUE,
    make         VARCHAR(50)  NOT NULL,
    model        VARCHAR(50)  NOT NULL,
    year         INTEGER      NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE components (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id   BIGINT       NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    type         VARCHAR(50)  NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'OK',
    installed_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_components_vehicle ON components (vehicle_id);

CREATE TABLE maintenance_records (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id   BIGINT       NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    component_id BIGINT       REFERENCES components (id) ON DELETE SET NULL,
    type         VARCHAR(50)  NOT NULL,
    description  TEXT,
    performed_at TIMESTAMPTZ  NOT NULL,
    cost         NUMERIC(12, 2)
);
CREATE INDEX idx_maintenance_vehicle ON maintenance_records (vehicle_id, performed_at DESC);

CREATE TABLE telemetry (
    vehicle_id       BIGINT           NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    ts               TIMESTAMPTZ      NOT NULL,
    lat              DOUBLE PRECISION,
    lng              DOUBLE PRECISION,
    speed            DOUBLE PRECISION,
    engine_temp      DOUBLE PRECISION,
    rpm              DOUBLE PRECISION,
    battery_voltage  DOUBLE PRECISION,
    fuel_level       DOUBLE PRECISION,
    vibration        DOUBLE PRECISION,
    tyre_pressure_fl DOUBLE PRECISION,
    tyre_pressure_fr DOUBLE PRECISION,
    tyre_pressure_rl DOUBLE PRECISION,
    tyre_pressure_rr DOUBLE PRECISION,
    brake_pad_wear   DOUBLE PRECISION,
    dtc_codes        TEXT[]           NOT NULL DEFAULT '{}',
    -- Simulator-only ground-truth label for ML training; NULL for real or healthy readings.
    injected_fault   TEXT,
    PRIMARY KEY (vehicle_id, ts)
);

SELECT create_hypertable('telemetry', 'ts');
