CREATE TABLE alerts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id   BIGINT       NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    component    VARCHAR(50)  NOT NULL,
    severity     VARCHAR(20)  NOT NULL,
    message      TEXT         NOT NULL,
    -- RULE (threshold rules in application.yml) or ML (anomaly model).
    source       VARCHAR(10)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    acknowledged BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_alerts_vehicle_created ON alerts (vehicle_id, created_at DESC);

-- At most one open alert per vehicle/component/severity/source, enforced by the database.
CREATE UNIQUE INDEX uq_alerts_open ON alerts (vehicle_id, component, severity, source) WHERE NOT acknowledged;
