-- Phase 2: driving events and trips, both derived from telemetry by the backend's driving analyser.
CREATE TABLE driving_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT           NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    -- HARSH_BRAKING, RAPID_ACCELERATION, SPEEDING, SHARP_CORNERING, EXCESSIVE_IDLING, FUEL_DROP, LOW_EFFICIENCY
    type       VARCHAR(30)      NOT NULL,
    severity   VARCHAR(10)      NOT NULL,   -- LOW, MEDIUM, HIGH
    ts         TIMESTAMPTZ      NOT NULL,
    lat        DOUBLE PRECISION,
    lng        DOUBLE PRECISION,
    -- The measurement behind the event: m/s^2, km/h, seconds or litres depending on type.
    value      DOUBLE PRECISION NOT NULL,
    detail     TEXT             NOT NULL
);
CREATE INDEX idx_driving_events_vehicle_ts ON driving_events (vehicle_id, ts DESC);

CREATE TABLE trips (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id     BIGINT           NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    started_at     TIMESTAMPTZ      NOT NULL,
    ended_at       TIMESTAMPTZ      NOT NULL,
    start_lat      DOUBLE PRECISION,
    start_lng      DOUBLE PRECISION,
    end_lat        DOUBLE PRECISION,
    end_lng        DOUBLE PRECISION,
    distance_km    DOUBLE PRECISION NOT NULL,
    duration_s     BIGINT           NOT NULL,
    avg_speed_kmh  DOUBLE PRECISION NOT NULL,
    max_speed_kmh  DOUBLE PRECISION NOT NULL,
    idle_s         BIGINT           NOT NULL,
    fuel_used_l    DOUBLE PRECISION NOT NULL,
    events_count   INTEGER          NOT NULL,
    -- Sum of event weight x severity multiplier; the driver score is derived from this and distance_km.
    penalty_points DOUBLE PRECISION NOT NULL,
    driver_score   DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_trips_vehicle_started ON trips (vehicle_id, started_at DESC);
