CREATE TABLE maintenance_recommendations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id            BIGINT       NOT NULL REFERENCES vehicles (id) ON DELETE CASCADE,
    component             VARCHAR(50)  NOT NULL,   -- brakes, battery, tyres, engine, fuel
    action                VARCHAR(100) NOT NULL,
    priority              VARCHAR(10)  NOT NULL,   -- LOW, MEDIUM, HIGH, URGENT
    recommended_by        DATE         NOT NULL,
    -- Plain-English list of the evidence the rules fired on.
    reason                TEXT         NOT NULL,
    status                VARCHAR(12)  NOT NULL DEFAULT 'OPEN',   -- OPEN, SCHEDULED, DONE, DISMISSED
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    completed_at          TIMESTAMPTZ,
    -- The maintenance record created when this was marked DONE.
    maintenance_record_id BIGINT       REFERENCES maintenance_records (id) ON DELETE SET NULL
);
CREATE INDEX idx_recommendations_status ON maintenance_recommendations (status, priority);

-- At most one recommendation in play per vehicle and component.
CREATE UNIQUE INDEX uq_recommendations_active ON maintenance_recommendations (vehicle_id, component)
    WHERE status IN ('OPEN', 'SCHEDULED');
