-- Phase 3: dashboard users and an audit trail of what they did.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    -- BCrypt. The first admin is created at startup from ADMIN_USERNAME / ADMIN_PASSWORD, never from a migration.
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('ADMIN', 'FLEET_MANAGER', 'TECHNICIAN', 'VIEWER')),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Refresh tokens carry this number; raising it (logout, password or role change) invalidates them all.
    token_version INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE audit_log (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Kept as text, not a foreign key, so the trail survives changes to the user.
    username  VARCHAR(50)  NOT NULL,
    action    VARCHAR(30)  NOT NULL,   -- ACKNOWLEDGE, COMPLETE, DISMISS, SCHEDULE, REOPEN, CREATE, UPDATE, DELETE, GENERATE
    entity    VARCHAR(30)  NOT NULL,   -- alert, recommendation, maintenance_record, user, report
    entity_id BIGINT,
    detail    TEXT
);
CREATE INDEX idx_audit_log_ts ON audit_log (ts DESC);
