-- Phase 3: generated reports. The file itself is in MinIO under object_key.
CREATE TABLE reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(30)  NOT NULL,   -- FLEET_HEALTH, MAINTENANCE, DRIVER_BEHAVIOUR, FUEL
    format      VARCHAR(10)  NOT NULL,   -- PDF, XLSX
    period_from DATE         NOT NULL,
    period_to   DATE         NOT NULL,   -- inclusive
    created_by  VARCHAR(50)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    object_key  VARCHAR(200) NOT NULL,
    size_bytes  BIGINT       NOT NULL
);
CREATE INDEX idx_reports_created ON reports (created_at DESC);
